# Generated by Django 5.1 on 2024-08-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_number', models.IntegerField()),
                ('Address', models.TextField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
